version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: $CONTAINER_NAME
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_PORT=$APP_PORT
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon index.js --legacy-watch

networks:
  app-network:
    driver: 'bridge'

volumes:
  node_modules: